sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
src/main.ts,\
src/app.module.ts,\
src/**/*.module.ts,\
src/**/*.dto.ts,\
src/**/*.entity.ts,\
src/**/*.enum.ts,\
src/auth/github.strategy.ts,\
src/auth/jwt.strategy.ts,\
src/auth/local.strategy.ts,\
src/auth/refresh-token.strategy.ts,\
src/common/utils/environment.util.ts,\
src/challenge/utils/css-battle-score.util.ts,\
src/code-execution/code-execution.service.ts,\
src/storage/image-storage.service.ts,\
src/review/review.service.ts,\
src/match/match.service.ts
