sonar.coverage.exclusions=\
src/main.ts,\
src/app.module.ts,\
src/**/*.module.ts,\
src/**/*.dto.ts,\
src/**/*.entity.ts,\
src/**/*.enum.ts,\
src/auth/github.strategy.ts,\
src/auth/jwt.strategy.ts,\
src/auth/local.strategy.ts,\
src/auth/refresh-token.strategy.ts
