export enum ChallengeTopic {
  ARRAY = 'Array',
  STRING = 'String',
  HASH_TABLE = 'Hash Table',
  LINKED_LIST = 'Linked List',
  STACK = 'Stack',
  QUEUE = 'Queue',
  HEAP_PRIORITY_QUEUE = 'Heap (Priority Queue)',

  TREE = 'Tree',
  BINARY_TREE = 'Binary Tree',
  BINARY_SEARCH_TREE = 'Binary Search Tree',
  GRAPH = 'Graph',
  TRIE = 'Trie',
  UNION_FIND = 'Union Find',

  SORTING = 'Sorting',
  SEARCHING = 'Searching',
  BINARY_SEARCH = 'Binary Search',
  TWO_POINTERS = 'Two Pointers',
  SLIDING_WINDOW = 'Sliding Window',
  BACKTRACKING = 'Backtracking',

  DYNAMIC_PROGRAMMING = 'Dynamic Programming',
  GREEDY = 'Greedy',
  MATH = 'Math',
  BIT_MANIPULATION = 'Bit Manipulation',
  RECURSION = 'Recursion',
  MEMOIZATION = 'Memoization',

  DEPTH_FIRST_SEARCH = 'Depth-First Search',
  BREADTH_FIRST_SEARCH = 'Breadth-First Search',
  TOPOLOGICAL_SORT = 'Topological Sort',
  SHORTEST_PATH = 'Shortest Path',

  MATRIX = 'Matrix',
  PREFIX_SUM = 'Prefix Sum',
  SEGMENT_TREE = 'Segment Tree',
  BINARY_INDEXED_TREE = 'Binary Indexed Tree',
  GEOMETRY = 'Geometry',
  DATABASE = 'Database',
  SHELL = 'Shell',
  CONCURRENCY = 'Concurrency',
  ORDERED_SET = 'Ordered Set',
  MONOTONIC_STACK = 'Monotonic Stack',
  ENUMERATION = 'Enumeration',
}
